# Generated by Django 5.0.4 on 2024-04-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0003_rename_first_name_project_f_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auther',
            old_name='email_address',
            new_name='email_addr',
        ),
    ]
