# Generated by Django 5.0.4 on 2024-04-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0004_rename_email_address_auther_email_addr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
